[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[inet_http_server]
port=0.0.0.0:9001
username=exporter
password=exporter-password

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001
username=exporter
password=exporter-password

[program:supervisord-metrics-exporter]
command=/usr/local/bin/supervisord-metrics-exporter -supervisor.url http://127.0.0.1:9001/RPC2 -supervisor.username exporter -supervisor.password exporter-password -web.listen.address :9002 -web.metrics.endpoint /metrics
autostart=true
autorestart=true
startsecs=2
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dummy-api]
command=/usr/local/bin/dummy-api
autostart=true
autorestart=true
startsecs=2
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dummy-worker]
command=/usr/local/bin/dummy-worker
autostart=true
autorestart=true
startsecs=2
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
